import {
  BarChart3,
  BriefcaseBusiness,
  CalendarDays,
  ChartPie,
  CheckCircle2,
  ClipboardList,
  Compass,
  Database,
  FileText,
  FolderKanban,
  Globe2,
  GraduationCap,
  Handshake,
  Lightbulb,
  LineChart,
  Link2,
  Megaphone,
  MessageSquareText,
  Rocket,
  Sparkles,
  Target,
  UsersRound,
} from "lucide-react";
import type { IconMap } from "@/types/content";

export const iconMap: IconMap = {
  barChart: BarChart3,
  briefcase: BriefcaseBusiness,
  calendar: CalendarDays,
  chartPie: ChartPie,
  checkCircle: CheckCircle2,
  clipboard: ClipboardList,
  compass: Compass,
  database: Database,
  fileText: FileText,
  folder: FolderKanban,
  globe: Globe2,
  graduationCap: GraduationCap,
  handshake: Handshake,
  lightbulb: Lightbulb,
  lineChart: LineChart,
  link: Link2,
  megaphone: Megaphone,
  messages: MessageSquareText,
  rocket: Rocket,
  sparkles: Sparkles,
  target: Target,
  users: UsersRound,
};
